### ISSUE TITLE
Login doesn't work.

### ISSUE THREAD

**Issue by Dravenex** [ThScEo/AutoForge#1]
Login doesn't work. Tested on de18 and de22 Server. SID and Key seems to be ok - but error message "check credentials" appears while trying to login.

**Comment by ThScEo** [comment]
Hi,

The bot was outdated; A new release is available in the "Releases" section, you should not encounter this issue.

**Comment by Wilsoonwillnow** [comment]
Hi
Unfortunately, when trying to authorize the error: "Expecting value: line 1 column 1 (char 0)
Error when login. Check your credentials or sid and user key"

**Comment by ThScEo** [comment]
> Hi Unfortunately, when trying to authorize the error: "Expecting value: line 1 column 1 (char 0) Error when login. Check your credentials or sid and user key"

Hi, can you please open a new issue, and specify the server you are playing on? Thank you.
