### ISSUE TITLE
wish

### ISSUE THREAD

**Issue by AlexFox002** [ThScEo/AutoForge#12]
- Allocate forge points over 5 to research (friends)

- Collects hidden rewards

**Comment by ThScEo** [comment]
Hello,

The latest release add the "**Collect hidden rewards**" feature.

**Comment by AlexFox002** [comment]
OK. Will there be a function to transfer points to a friend in the great buildings?

**Comment by AlexFox002** [comment]
Thanks

**Comment by ThScEo** [comment]
> OK. Will there be a function to transfer points to a friend in the great buildings?

Such feature will be added later.

**Comment by Looty20** [comment]
Hi, your work's amazing. However, I seem to struggle with anchoring. The window doesn't scale and thus I'm unable to start the process (The button is covered with the "Residential" tab). Could you anchor it to the sides in the next update, please? :)

**Comment by ThScEo** [comment]
Hi, thank you :) Ohhh okay, sorry ! Will be done! :)
