### ISSUE TITLE
Connection failed. Error when login. Check your credentials or sid and user key

### ISSUE THREAD

**Issue by paperboy11** [ThScEo/AutoForge#14]
No matter what browser i use i cannot connect at all? is there a weird connection bug or something silly just being missed?

**Comment by ThScEo** [comment]
When opening an issue, please give the maximum of details please:
- Server your are playing on
- AutoForge version
- Anything you think can be useful
Thank you.

**Comment by paperboy11** [comment]
Do you have discord? i for sure dont wanna dox myself but ill give what i can.

 us22

Connection failed.
Error when login. Check your credentials or sid and user key

**Comment by paperboy11** [comment]
btw when i put the wrong creds in it gives me this Connection failed : Sorry, your session has expired. Please log in again.
Error when login. Check your credentials or sid and user key

Im also on 0.3.9

**Comment by ThScEo** [comment]
Thank your for your reply. 

1.  The "Sorry, your session has expired. Please log in again." message will occur each time you enter wrong credentials OR you enter right credentials but your session is really expired. That is the message sent by FoE in theses two cases.
2.  I will try on us22 server and publish an update asap

_PS: The next update will also include auto-collection of hidden rewards_

**Comment by paperboy11** [comment]
yeah so the initial error message is me doing it on the correct server so it seems with all the correct creds just US22 seems to either have protection or misconfig.   Ill eagerly be awaiting, i know a few people who have tried to use it but couldn't log in so figured it was a trap or something. Happy to hear this

**Comment by ThScEo** [comment]
Hello,

For instance AutoForge can’t work for Viking World and other bonuses map, but this feature will be added later.
I tried to connect to us22, with latest release of AutoForge (0_3_10) and it seems ok. 

Can you please try to connect with your account again, and if it’s not working, with a fresh account without lot of things unlocked, and let me know for theses two cases if you encounter an issue?

Thank you

**Comment by paperboy11** [comment]
Just tried it and i still get this Connection failed.
Error when login. Check your credentials or sid and user key

I'm quite positive im using all the correct strings and everything as directed. I do use python scraping scripts that use most same methods. Again, willing to share more information privately to help you debug

**Comment by ThScEo** [comment]
Are you sure you wrote the URL correctly? eg: **https://us23.forgeofempires.com/game/** ? the **https://** is needed, without it it won't work.

_Feel free to send email at adm.forgeofbot@gmail.com_

Thank you

**Comment by paperboy11** [comment]
proton to proton coming

**Comment by paperboy11** [comment]
Actually whatever you did made it work, Testing everything out now
