### ISSUE TITLE
rat shit

### ISSUE THREAD

**Issue by Pasxeegamer** [ThScEo/AutoForge#18]
this is just stealing your foe tokens, all of it arent working!! please dont use

**Comment by paperboy11** [comment]
What?

**Comment by paperboy11** [comment]
> this is just stealing your foe tokens, all of it arent working!! please dont use

explain? the app works perfect

**Comment by ThScEo** [comment]
> this is just stealing your foe tokens, all of it arent working!! please dont use

Are you stupid? The goal of asking thé user his tokens is to allow the connection. Even if that was a « shit rat » you just have to log In from the FoE website to generate new token, and the old token will become invalid. 
If you don’t know how things work, please don’t pollute this repo with useless issues.
