### ISSUE TITLE
Error when login

### ISSUE THREAD

**Issue by Wilsoonwillnow** [ThScEo/AutoForge#2]
Expecting value: line 1 column 1 (char 0)
Error when login. Check your credentials or sid and user key"
ru11

**Comment by Griladorth** [comment]
you need to check the sid or the user key or the url.
i can login ok

**Comment by ThScEo** [comment]
> Expecting value: line 1 column 1 (char 0) Error when login. Check your credentials or sid and user key" ru11

It may be because you are playing on RU servers. I will investigate on your issue and keep you updated.
