### ISSUE TITLE
no worck

### ISSUE THREAD

**Issue by GoAciccio** [ThScEo/AutoForge#20]
hello dear keep giving me connection failed, I do all the required procedures. a help?

**Comment by ThScEo** [comment]
Can you tell me what server you are playing on?

**Comment by GoAciccio** [comment]
italia

**Comment by GoAciccio** [comment]
?

**Comment by GoAciccio** [comment]
?

**Comment by ThScEo** [comment]
I’ll investigate today. I’ll keep you informed

**Comment by ThScEo** [comment]
I tried to connect with a fresh account to it servers, I didn't encountered any connection issue. Can you please try with a new account ? 
Can you please check that the SID, User Key and the url is fine ? The url should be  something like "https://it11.forgeofempires.com/game/"

**Comment by GoAciccio** [comment]
https://it8.forgeofempires.com/game/"  for me

**Comment by GoAciccio** [comment]
even with a new account, gives the probblem
