### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by raxorpro99** [ThScEo/AutoForge#21]
When logging in I get the following error:

```
Error parsing message : Sorry, an internal error occurred. Please try again later {'title': 'Exception', 'message': 'Sorry, an internal error occurred. Please try again later', '__class__': 'Error'}
Connection failed.
Error when login. Check your credentials or sid and user key

```

P.s: SID and key are correct.
It was working fine until yesterday.

**Comment by ThScEo** [comment]
Hey. Thank you, i will make an update of the backend and keep you informed asap

**Comment by JayseeXD** [comment]
This is now occuring again.

**Comment by ThScEo** [comment]
Hi. An update of the backend will be done in few days

**Comment by ThScEo** [comment]
The update is done. You should be able to connect now
