### ISSUE TITLE
Error at launch program

### ISSUE THREAD

**Issue by Jgalaio** [ThScEo/AutoForge#23]
hello friend.

I want to try your bot, but getting the error.

Unable to Check Release. how can I fix this? and the purchase form are working ?

**Comment by tomasfriedrich** [comment]
Same issue. Already discussed on youtube.

It is getting error just after running the file. I also tried to insert keys directly to config.json, but still not working

**Comment by ThScEo** [comment]
Hi guys. I'm sorry i thought nobody used the bot. I will fix the backend, and so you will be able to use the bot asap :)

**Comment by ThScEo** [comment]
You should be able to use the bot from now.

**Comment by Jgalaio** [comment]
> You should be able to use the bot from now.

tks a lot m8. you should put on ElitePVP or something. lots of people are looking for Bots, and none working ATM

**Comment by ThScEo** [comment]
Thank you, I've put it on Epvp, but it seems they don't accepted my thread for this time
