### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by Jgalaio** [ThScEo/AutoForge#24]
Hy m8, i alredy check my SID and User Key but always got this error.

Error parsing message : 
Sorry, an internal error has occurred. Try again later {'title': 'Exception', 'message': '
Sorry, an internal error has occurred. Try again later', '__class__': 'Error'}
Connection failed.
Error when login. Check your credentials or sid and user key

**Comment by ThScEo** [comment]
Hi. The update is done, you should be able to connect again.
