### ISSUE TITLE
Unable to collect with the last foe version

### ISSUE THREAD

**Issue by Abrahou** [ThScEo/AutoForge#26]
Hi ThScEo, 

I tried your bot.
Login succesfull work, but i can't collect automaticaly ressources from building

Are you aware of a limitation with the foe last update ? 

BR

**Comment by ThScEo** [comment]
Hi,

I’ll Check that today and let you know if I find any issue

**Comment by ThScEo** [comment]
You should be able to connect now

**Comment by Abrahou** [comment]
Hi ThScEo/AutoForge,

Thx for your answer.
Everything was working fine until i received an email from foe

-------
Hello Abegg,

Our system has detected that you are using prohibited software to interact
with our game.
Please remember that the use of bots, scripts, or other tools that give you
an unfair advantage is strictly prohibited in our game. We require you to
disable prohibited software immediately or additional penalties may follow.
Thank you for your cooperation.

Your Forge of Empires Team

So I had to stop using it.

BR
Abrahou

**Comment by xphantomdavex** [comment]
Hello, could you upload a picture of the email to imgur and the email it was sent from? to make sure its real

**Comment by Abrahou** [comment]
Hello,

It's not an email, it's a direct message from foe on my message center
https://i.imgur.com/R9WGI98.jpg

BR
