### ISSUE TITLE
Nothing is happening

### ISSUE THREAD

**Issue by lbn21** [ThScEo/AutoForge#28]
It connect but nothing is happening? There is no start button right?
New version: 1.249

**Comment by ThScEo** [comment]
Hi. You should see the big blue button "Run", then click on it. Tell me if there is a problem? :)

**Comment by lbn21** [comment]
I don't see any buttons. Am I blind?
https://i.imgur.com/EahyJG1.png

**Comment by lbn21** [comment]
@ThScEo sorted. I had my text & scale set to 150%. You may add to readme section to have it set to 100%
