### ISSUE TITLE
Last Update

### ISSUE THREAD

**Issue by Jgalaio** [ThScEo/AutoForge#29]
hy m8, since the last update the bot dont work.

Error parsing message : Lamentamos, ocorreu um erro interno. Tenta novamente mais tarde {'title': 'Exception', 'message': 'Lamentamos, ocorreu um erro interno. Tenta novamente mais tarde', '__class__': 'Error'}
Connection failed.
Error when login. Check your credentials or sid and user key

can you fix it pls?

**Comment by ThScEo** [comment]
Hi. It's fixed, thank you
