### ISSUE TITLE
error msg

### ISSUE THREAD

**Issue by CarniceroUy** [ThScEo/AutoForge#3]
when im runing the bot i have a erro msg and the bot stop the loop

Error when checking updates : 'updatedEntities'

**Comment by ThScEo** [comment]
Please can you specify the server you are playing on ? Have you checked your SID, user key and game url?

**Comment by CarniceroUy** [comment]
Im playing in mx server.
Now I can conecct and I can run it.
Now I have other problem:

the bot doesn't always collect or put to production, he do it randomly.

**Comment by ThScEo** [comment]
Can you send the log displayed in the bot please?

**Comment by CarniceroUy** [comment]
Connection done successfully
Beginning loop..
Fetching updates..
Checking entities..
Checking quests..
Checking neighbours..
Checking done..
End of loop..
Beginning loop..
Fetching updates..
Checking entities..
Starting production of entity P_FutureEra_Workshop4..
Harvesting entity P_FutureEra_Workshop4..
Starting production of entity P_FutureEra_Workshop4..
Starting production of entity P_FutureEra_Workshop4..
Starting production of entity P_FutureEra_Workshop4..
Starting production of entity P_FutureEra_Workshop4..
Starting production of entity P_FutureEra_Workshop4..
Starting production of entity P_FutureEra_Workshop4..
Starting production of entity P_FutureEra_Workshop4..
Harvesting entity P_FutureEra_Workshop4..
Harvesting entity P_FutureEra_Workshop4..
Harvesting entity P_FutureEra_Workshop4..
Checking quests..
Checking neighbours..
Checking done..

**Comment by ThScEo** [comment]
Thank you. It seems that everything is correct? Why are you telling  the bot is doing action randomly?

**Comment by CarniceroUy** [comment]
the log is correct but in forge of empires dont do the action.
sometimes it starts to produce and sometimes it doesn't, sometimes it collect up and sometimes it doesn't.

**Comment by ThScEo** [comment]
How do you check that everything is fine? If you use the bot while playing on your computer, you will not see the actions of the bot on your screen. If you want to check everything is ok, you should:
- run the bot
- after the bot ended his first loop,
- connect to your account with your computer, and check if production is started etc...

**Comment by CarniceroUy** [comment]
ok, i will do now

**Comment by TbbTR** [comment]
I checked the behavior. I have 7 farms, Set the production to 15min.
After a while i stoped the bot and reload the open browser.
Some productions of the farm are finished, some produce nothing.
Also many houses have finished coins but not all. I harvest all buildings before the start manually.

**Comment by CarniceroUy** [comment]
So... Im active the bot for 6hrs, and I waited for the bot to finish. 
I opened the chrome and open foe, I have some uncollected buildings and some collected

**Comment by TbbTR** [comment]
I can confirm that behavior.

**Comment by ThScEo** [comment]
With the new release you should see an error message if there was an error while harvesting/starting production of a building. Please keep me updated.

**Comment by ThScEo** [comment]
I found the cause of this issue, a release will be available soon ;)

**Comment by Gerchan** [comment]
Hello. Getting the same error, I am on latest release.

![AutoForge_mejOtT84KZ](https://user-images.githubusercontent.com/29171156/188085556-ffe329a6-05ac-4d85-a40f-04f065fc78d5.png)

**Comment by CarniceroUy** [comment]
now it works perfect.

Thx u bro, I can help you with something?

**Comment by Gerchan** [comment]
> now it works perfect.
> 
> Thx u bro, I can help you with something?

You don't get "Unable to star production for entity..." anymore? It's still happening to me :(

**Comment by CarniceroUy** [comment]
No, it's working fine

**Comment by ThScEo** [comment]
> Ok, tonight the bot was disconnected due to a connection error. I see the following: Starting production of entity P_FutureEra_Workshop2.. Starting production of entity P_FutureEra_Workshop2.. Starting production of entity P_FutureEra_Workshop2.. Starting production of entity P_FutureEra_Workshop2.. Starting production of entity P_FutureEra_Workshop2.. Unable to start production for entity.. Starting production of entity P_FutureEra_Workshop2.. Unable to start production for entity.. Starting production of entity P_FutureEra_Workshop2.. Unable to start production for entity.. Starting production of entity P_FutureEra_Workshop2.. Unable to start production for entity.. Starting production of entity P_FutureEra_Workshop2.. Unable to start production for entity..
> 
> Always start production in the same building and in the same buildings that can't produce

This is never the same building. The name displayed is the generic name of building. In next releases an unique ID of each building will be displayed, to make that more explicit.

**Comment by Gerchan** [comment]
> > Ok, tonight the bot was disconnected due to a connection error. I see the following: Starting production of entity P_FutureEra_Workshop2.. Starting production of entity P_FutureEra_Workshop2.. Starting production of entity P_FutureEra_Workshop2.. Starting production of entity P_FutureEra_Workshop2.. Starting production of entity P_FutureEra_Workshop2.. Unable to start production for entity.. Starting production of entity P_FutureEra_Workshop2.. Unable to start production for entity.. Starting production of entity P_FutureEra_Workshop2.. Unable to start production for entity.. Starting production of entity P_FutureEra_Workshop2.. Unable to start production for entity.. Starting production of entity P_FutureEra_Workshop2.. Unable to start production for entity..
> > Always start production in the same building and in the same buildings that can't produce
> 
> This is never the same building. The name displayed is the generic name of building. In next releases an unique ID of each building will be displayed, to make that more explicit.

For me it is definitely the same building, I have only one fruit farm and it never starts production, I have to begin a new loop after everything else is collected.

**Comment by ThScEo** [comment]
Okay thank you for your reply. Yes it is not suprising me that you received such message. In fact, if the bot don’t bug and act like normal player it will be much less flagged as bot, but if the bot bug and send a lot of incorrect messages to the server, the server would detect it. 

So, you should wait until next release to prevent your account from being banned

**Comment by CarniceroUy** [comment]
I will test the new version =)

**Comment by CarniceroUy** [comment]
ok, i cant connect.
Connection failed.
Error when login. Check your credentials or sid and user key

i tryed some times with diferentes logins

**Comment by ThScEo** [comment]
Hello,

**A new version of FoE was released recently**, so the bot needed to be updated again.  
_This behaviour will be upgraded soon, so the bot will no longer need one update each time FoE is updated._

_The issue should be resolved, please let me know._

**Comment by CarniceroUy** [comment]
Thx u for the work.
I tested it and the error continues

**Comment by ThScEo** [comment]
Hello,

A new release is available. This release add an "Error report" feature, automatically enabled, which will help me to find and fix bugs. 

Please download it, then try to connect, this will allow me to be able to consult the logs and fix the error

**Comment by CarniceroUy** [comment]
Hi bro, now with the new version run good. im testing now.
Thx u.

**Comment by CarniceroUy** [comment]
Entonces ahora no puedo conectarme, nuevamente me envía el mensaje "Error de conexión.
Error al iniciar sesión. Verifique sus credenciales o sid y contraseña"

estoy usando las credenciales correctas

**Comment by CarniceroUy** [comment]
Bro it's working good, thx u.
