### ISSUE TITLE
Suddenly getting login failure

### ISSUE THREAD

**Issue by ccbamatx** [ThScEo/AutoForge#32]
Message received on login attempt is:

Error parsing message : Sorry, an internal error occurred. Please try again later {'title': 'Exception', 'message': 'Sorry, an internal error occurred. Please try again later', '__class__': 'Error'}
Connection failed.
Error when login. Check your credentials or sid and user key

...I have been using this for a couple of weeks... I am properly inserting the credentials.

**Comment by ccbamatx** [comment]
Great... I have gotten blocked 3 or 4 times... any idea how they are discovering your process?

**Comment by reitut** [comment]
got this: 
Connection failed.
Error when login : local variable 'response' referenced before assignment
