### ISSUE TITLE
Can't login for the last week

### ISSUE THREAD

**Issue by inuxmedia** [ThScEo/AutoForge#37]
Always, connection failed, then tells me to check my sid and user, which I've repeatedly confirmed are correct. I've tried manually logging out and back in and updating the values.

![image](https://user-images.githubusercontent.com/648202/231611034-5e696e31-ed08-4af5-86d2-c7dd995ae661.png)

It's been running fine for weeks before this.

**Comment by ThScEo** [comment]
Hi, a new version of the bot is available, please upgrade, and keep me informed :)

**Comment by inuxmedia** [comment]
I'm still getting the same connection failed error. Confirmed the SID and user key are up to date, as well as my license key.

**Comment by ThScEo** [comment]
I think I've fixed it. Please downlaod the v0.4.4

**Comment by inuxmedia** [comment]
Fixed! Cheers!
