### ISSUE TITLE
Auto-Invest Forge Points not working

### ISSUE THREAD

**Issue by Zundarian** [ThScEo/AutoForge#39]
Hay. i cant enable the Check Box for "Auto-Invest Forge Points" (i have a paied licence)

Also i want to ask if its possible to save 

- Production Time
- Goods Time
- Neighbours Action
- Military Buildings
- Hidden rewards 

In the config file (may on release at the next version) So i dont have to set them up everytime i run the tool

**Comment by ThScEo** [comment]
Hi, 

My fault, I have not updated all licenses features, I do it right now ;)

About the save of the settings, Will be added next release :)
