### ISSUE TITLE
Login not possible de15

### ISSUE THREAD

**Issue by TbbTR** [ThScEo/AutoForge#4]
'y'
Error when login. Check your credentials or sid and user key

![image](https://user-images.githubusercontent.com/111305119/184685942-0a6f87f7-23bc-4159-bf39-c77ce2ef72df.png)

SID and UserKey are fine.

**Comment by ThScEo** [comment]
Please download the latest release. If the latest release resolves your issue, you can close it.

**Comment by TbbTR** [comment]
Still the same error with new release.

**Comment by ThScEo** [comment]
I made a mistake when solving the bug. You can download the latest release now, the issue should be fixed. Keep me updated.
