### ISSUE TITLE
not work after update

### ISSUE THREAD

**Issue by xazes** [ThScEo/AutoForge#42]
Hi Since two days after update i get:
`Failed to fetch metadatas. AutoForge may not work properly.
Connection failed.
Error when login. Check your credentials or sid and user key`

I checked twice the sid and user id but autoforge cant connect

**Comment by xazes** [comment]
Error parsing message : Ein interner Fehler ist aufgetreten. Bitte versuche es später noch einmal. {'title': 'Exception', 'message': 'Ein interner Fehler ist aufgetreten. Bitte versuche es später noch einmal.', '__class__': 'Error'}

**Comment by ThScEo** [comment]
Fixed
