### ISSUE TITLE
Error on Login

### ISSUE THREAD

**Issue by User59861** [ThScEo/AutoForge#44]
Error parsing message : Sorry, an internal error occurred. Please try again later {'title': 'Exception', 'message': 'Sorry, an internal error occurred. Please try again later', '__class__': 'Error'}
Failed to fetch metadatas. AutoForge may not work properly.
Connection failed.
Error when login. Check your credentials or sid and user key

....Credentials are correct.

**Comment by ThScEo** [comment]
Hi,

Update has been done, should be fixed :)
