### ISSUE TITLE
Error login !

### ISSUE THREAD

**Issue by sinanelms** [ThScEo/AutoForge#48]
hi, so far there was no problem but since 11/07/2023 i am getting the following error, make sure i entered "sid" and "user key" correctly

```
Error parsing message : Üzgünüz, dahili bir hata oluştu. Lütfen daha sonra yeniden dene {'title': 'Exception', 'message': 'Üzgünüz, dahili bir hata oluştu. Lütfen daha sonra yeniden dene', '__class__': 'Error'}
Failed to fetch metadatas. AutoForge may not work properly.
Connection failed.
Error when login. Check your credentials or sid and user key
```

**Comment by madmaxcryptox** [comment]
Hi @ThScEo ,
 Can you please provide a new release to fix this issue? The version 48 is failing with the error above.

**Comment by ThScEo** [comment]
Hi, a fix will be available this week, sorry for the inconveniance , all paid license will have few days added freely

**Comment by ThScEo** [comment]
Hi. Backend has been updated.
