### ISSUE TITLE
Not harvesting buildings

### ISSUE THREAD

**Issue by SMillerTX** [ThScEo/AutoForge#49]
Using the free license key and everything connects successfully. I can see everything under "How much I have". However, when it runs, nothing happens. I thought the free version at least collected coins from houses and harvested goods from goods and production buildings. Here is the error I get:

Fetching updates..
Checking entities..
Your license key is not allowing you to harvest buildings..

**Comment by ThScEo** [comment]
Hi. Backend has been updated.
