### ISSUE TITLE
Error on AutoForge

### ISSUE THREAD

**Issue by User59861** [ThScEo/AutoForge#51]
Error parsing message : Sorry, an internal error occurred. Please try again later {'title': 'Exception', 'message': 'Sorry, an internal error occurred. Please try again later', '__class__': 'Error'}
Failed to fetch metadatas. AutoForge may not work properly.
Connection failed.
Error when login. Check your credentials or sid and user key

**Comment by ThScEo** [comment]
Hi, a fix will be available this week, sorry for the inconveniance , all paid license will have few days added freely

**Comment by ThScEo** [comment]
Hi. Backend has been updated.
