### ISSUE TITLE
Have you stopped developing this tool?

### ISSUE THREAD

**Issue by User59861** [ThScEo/AutoForge#53]
Have you stopped developing this tool?

**Comment by ThScEo** [comment]
Hi. 

No, I am doing some maintenance to keep the tool compatible with latest versions of Foe. I don't check every days if there is a new Foe update, so if the tool is outdated, anyone is invited to open an issue, to let me know that i must make an update of the tool :)

Depending on users amount using the tool, i can spend time to develop new features/upgrade the tool.

**Comment by operdrix** [comment]
Hi !
For me, it's not possible to login since 1 week.
I have "Connexion failed" message.
Thanks for your job :)

**Comment by User59861** [comment]
I am still getting the same error as last month.  That error is.

Error parsing message : Sorry, an internal error occurred. Please try again later {'title': 'Exception', 'message': 'Sorry, an internal error occurred. Please try again later', '__class__': 'Error'}
Failed to fetch metadatas. AutoForge may not work properly.
Connection failed.
Error when login. Check your credentials or sid and user key

**Comment by ThScEo** [comment]
Hi, thanks for the info! I’ll make an update tonight, the bot will work after :) 

Have a good day, and next time the bot need an update to be compatible with the last FoE version, please advise me :)

**Comment by ThScEo** [comment]
Update has been done

**Comment by operdrix** [comment]
Hi, I don't see the new release.
