### ISSUE TITLE
No.exe

### ISSUE THREAD

**Issue by DibbleDabbleDoo** [ThScEo/AutoForge#54]
Have downloaded and unzipped multiple times, there is no .exe. Haven't ever had this issue before any help would be great. Downloaded the newest release but when unzipped there's no execute "Run". I have adjusted said screen to 100%, I have downloaded everything and followed directions to a "T". Any help would be greatly appreciated or if someone can email the file as the current download is not working.

**Comment by ThScEo** [comment]
Hi.
I think your antivirus is blocking the .exe file. You should try to add an exception or to deactivate your antivirus then download again. I advise you to not download file sent by someone by mail, that may be not the real bot.
