### ISSUE TITLE
Upgrade Needed

### ISSUE THREAD

**Issue by User59861** [ThScEo/AutoForge#55]
I am getting....

Error parsing message : Sorry, an internal error occurred. Please try again later {'title': 'Exception', 'message': 'Sorry, an internal error occurred. Please try again later', '__class__': 'Error'}
Failed to fetch metadatas. AutoForge may not work properly.
Connection failed.
Error when login. Check your credentials or sid and user key

**Comment by ThScEo** [comment]
Hi. 

- Can you try to re-download the latest release, and double check your sid etc? 
- What is your server?

Thank you

**Comment by DibbleDabbleDoo** [comment]
" Unable to check release. AutoForge cant run."

**Comment by User59861** [comment]
That works on server https://us9.forgeofempires.com/game/

...You mentioned you could refresh my key.  Would you like me to post my old key here?

**Comment by ThScEo** [comment]
Hi, 
Send me your key at thsceo@proton.me
