### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by operdrix** [ThScEo/AutoForge#57]
Hi,
I have this message : 
"Connection failed.
Error when login. Check your credentials or sid and user key"

I have checked ma SID and user key many times but it doesn't work.
The URL is https://fr22.forgeofempires.com/game

Thanks for your help !

**Comment by Zercies29** [comment]
I have the Same issue, any fix?

**Comment by ThScEo** [comment]
Hi, sorry for late response! The backend has been updated you should be able to connect 👍

**Comment by Zercies29** [comment]
This appears to be an issue again.  I just purchased a month key and when I went to enter it I am getting the same "Check your credentials or sid and user key" error again as before. please advise.  Thanks

**Comment by ThScEo** [comment]
Update done, you should be able to connect.
