### ISSUE TITLE
"Check your credentials or sid and user key" error again as before - Please Advise

### ISSUE THREAD

**Issue by Zercies29** [ThScEo/AutoForge#58]
This appears to be an issue again.  I just purchased a month key and when I went to enter it I am getting the same "Check your credentials or sid and user key" error again as I was 4 days ago.  It was working a few hours ago but now it is not.

**Comment by ThScEo** [comment]
Hello.
I've just checked, FoE has not updated. I have checked that connection is possible via a test account and it is. Please check:
- your SID and user key
- That your account is not banned, by manually connecting to FoE.

Important: every time you connect from your PC to Foe (not via AutoForge), a new SID and user key are generated, and you need to update them in AutoForge.

**Comment by Zercies29** [comment]
Does this apply to the mobile app as well?  Meaning, If I check my phone
App will it create a new SID and stop AutoForge?

It is working now but before I checked and double checked and rechecked
over and over and over and it would not work so I don't know what was
happening but something was preventing me from authenticating.

Thanks

Michael C

**Comment by ThScEo** [comment]
Hello,

I haven't tested it via the mobile application. However, I think that each time you connect via your mobile, a sid and a user key are generated again.
