### ISSUE TITLE
Features not working on Premium

### ISSUE THREAD

**Issue by Zercies29** [ThScEo/AutoForge#59]
Polivate players automatically. (Premium)
Collect hidden rewards automatically. (Premium)

These features do not appear to be working even with a premium key.

**Comment by ThScEo** [comment]
Hi. 

How did you checked/noticed that theses features are not working?

1. Connect to Foe With your browser
2. Watch for hidden rewards (don't click on them, just watch where are they)
3. Run Autoforge with Hidden rewards collect
4. Log again in Foe form your browser, check that the hiddens rewards you saw at step 2 are always here. If you don't see them, that means AutoForge is working normally

Please tell me,

Thank you
