### ISSUE TITLE
[Feature Request] Summarize Earnings

### ISSUE THREAD

**Issue by TbbTR** [ThScEo/AutoForge#6]
Would be perfect to see the summarize earnings from the start of farming.
At the moment only the earnings of the last run are shown.

**Comment by ThScEo** [comment]
Hello,

This is a good idea. It will be included in next release :)

**Comment by ThScEo** [comment]
Hi. The latest release (0.4.1) add this feature. See [Releases section](https://github.com/ThScEo/AutoForge/releases/tag/v0.4.1)
