### ISSUE TITLE
Premium not working on VM

### ISSUE THREAD

**Issue by RangerBarlow** [ThScEo/AutoForge#60]
Hello, love the AutoForge program! purchased the Premium version and use it just fine on my desktop, but when I try to load it up on my VM of Win11 and use my Premium key all functions are "Disabled", it works with the free key though. So are the Premium keys only good for 1 computer?

My desktop has a really large power consumption and I'd like to run this program 24/7 on my servers Virtual Machine.

**Comment by ThScEo** [comment]
Hello,

Thanks :)
Yes, the premium license is locked for one computer.

Thank you
