### ISSUE TITLE
Unable to check version. AutoForge can't run. Error

### ISSUE THREAD

**Issue by RoRoFoE** [ThScEo/AutoForge#65]
Hello. I have been trying over and over to get this working, I followed all the steps and this error keeps popping up. Please tell me how to fix this and ask anything needed.

**Comment by ThScEo** [comment]
Hello,
Thank you for notice me. I’ll update the backend and the connection will be ok. I’ll tell you when thats’ok.

**Comment by Daytona600** [comment]
Have the same problem, any updates?
Thank you

**Comment by ThScEo** [comment]
Hi, update has been done you should be able to use Autoforge :)
