### ISSUE TITLE
 AutoForge  Error on run 

### ISSUE THREAD

**Issue by geoman288** [ThScEo/AutoForge#66]
When run the autoforge.exe have this error : version game 1280 

Error
"Unable to cheack release. Autoforge can't run"

**Comment by ThScEo** [comment]
Hey. 
Thanks for using autoForge.

I Will make an update tonight and you’ll be able to Connect.

**Comment by geoman288** [comment]
Multi-language support should be added to the application, 
I can help for the Greek language.
thanks

**Comment by ThScEo** [comment]
Hey. You should be able to connect right now :)

About the multilanguages support, It will be added in few moments, thank you!
