### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Ezziake** [ThScEo/AutoForge#68]
when I try to login I get the error 
"Error parsing message: Error {'title': 'Sorry, an error has occurred!', 'message': 'Sorry, an internal error occurred. Please try again later', '__class__': ' Error'}
Failed to fetch metadata. AutoForge may not work properly.
Connection failed.
Error when login. Check your credentials or sid and user key"

I followed all the steps and entered everything correctly

**Comment by ThScEo** [comment]
Hey.

Sorry for that. I updated the backend so you should be able to connect now , thanks ;)
