### ISSUE TITLE
Free key is not working

### ISSUE THREAD

**Issue by cangokcer** [ThScEo/AutoForge#69]
Hi,

I used your free key (EITTX-IQPXX-NURZG-WKWYK) but even I am successfully connect to my account I see all free utils are also unchecked/disabled. So I can not test it.

Harvest all buildings automatically. (Free)
Start production automatically of
Goods buildings (Free)
Supplies buildings (Free)
Military buldings (Free)

these are all disabled.,
thanks
![image](https://github.com/ThScEo/AutoForge/assets/60292093/e1c260b5-09e0-491f-83fc-1ec31345c851)

**Comment by ThScEo** [comment]
Hi,

Sorry each key is limited ton 600 users, i didnt noticed the limit was reached. You can use this key : DFNHD-TMRSA-UYFUV-XFCZB.

Thank you

**Comment by cangokcer** [comment]
Hi friend,

Thank you for the key but still the same with the new key.

fields are disabled and I get same error that "your license does not support" errror. 

thanks anyway for your help
regards

**Comment by cangokcer** [comment]
Hi Friend,

I setup program to another PC and it worked with the new key. I noticed that my PC gives an error below that may cause to problem. This is just to inform you.

![image](https://github.com/ThScEo/AutoForge/assets/60292093/ab3bce74-ba1b-4294-bbc3-d56aab62a2b4)
