### ISSUE TITLE
Error while log-in with free key

### ISSUE THREAD

**Issue by Magalor-GitHub** [ThScEo/AutoForge#70]
`Error parsing message : Error {'title': 'Oops! Si è verificato un errore.', 'message': 'Spiacente, si è verificato un errore interno. Riprova più tardi.', '__class__': 'Error'}`

This is the output error.

**Comment by ThScEo** [comment]
Hello,

- which key did you use?
- did you checked your SID and User key ? (See Readme to know How to get them)

thanks

**Comment by Magalor-GitHub** [comment]
yes checked both sid and user key.....i used both of the free keys same output error

**Comment by ThScEo** [comment]
Sorry, FoE made an update i did not noticed. issue solved you should be able to Connect now ;)
