### ISSUE TITLE
Free keys do not allow any actions

### ISSUE THREAD

**Issue by CursedBoss** [ThScEo/AutoForge#71]
Good day, both free keys do not allow harvest right now. Last year I use - all working good.

Beginning loop..
Sleep time : 262s
Fetching updates..
Checking entities..
Your license key is not allowing you to harvest buildings..
Checking quests..
Your license key is not allowing you to getting rewards for quests..
Checking neighbours..
Your license key is not allowing you to polivate players..
Checking hidden rewards..
Your license key is not allowing you to harvest hidden rewards..
Checking done..
Sleep time : 259s

**Comment by ThScEo** [comment]
Hello,

Thank you for your reporting. I will do some investigations. An update will be available in few days ;)

**Comment by ThScEo** [comment]
Double-check you didn't made a typo when writing the license key please. This error occurs when the license is not valid or expired (eg: a random string).

**Comment by CursedBoss** [comment]
Right now. Both keys shows this error.

![image](https://github.com/user-attachments/assets/97aaed7d-955b-452d-a2c9-4d7de910188a)

**Comment by ThScEo** [comment]
Hello,

Sorry for that. Can you download the latest release (v0.4.9b), then try again? <b>It will not work again, but i will be able to see logs and solve the issue</b>.

Thank you!

**Comment by CursedBoss** [comment]
right now it shows 2 errors windows:
1:
![image](https://github.com/user-attachments/assets/aab943cb-974c-4874-aefb-f6db1e37eaa0)


2:
![image](https://github.com/user-attachments/assets/42514818-cb6a-4237-8e42-4e7322792422)
