### ISSUE TITLE
Connection failed. Error when login : local variable 'response' referenced before assignment

### ISSUE THREAD

**Issue by Golder2024** [ThScEo/AutoForge#73]
Tool dont Start. Version 0.4.9b
Keys checked -> ok

Message: 
Connection failed.
Error when login : local variable 'response' referenced before assignment

![image](https://github.com/user-attachments/assets/34fb9eb3-f014-4aec-8b65-e6c4b0081b5c)

**Comment by ThScEo** [comment]
Hello

You can try the new release  (0.4.9c). **You will probably get another error, but il will help me to solve the issue.**
Thanks and sorry for the inconvenience!

**Comment by Golder2024** [comment]
Thx, i try the new Version at wednesday.

**Comment by Golder2024** [comment]
AutoForgev0_5_1 works fine, THX
