### ISSUE TITLE
Key outdated

### ISSUE THREAD

**Issue by Golder2024** [ThScEo/AutoForge#74]
Hello, after the trial period I only want to use the free version, which key do I have to enter?
The following message always appears 

![image](https://github.com/user-attachments/assets/c2cfc18e-a534-4f41-b16d-9c7bc3cbd8f7)

Thx 4 help

**Comment by ThScEo** [comment]
Hi,

The Free version  has changed. Now, you have access to all features for Free using the trial key.
When the trial key is expired, that means you had enough time to know if you like the software and want to pay 4€/month to keep access to all features.

Is it clear?

Thank you :)

**Comment by Golder2024** [comment]
Ok, thank you.
This means that there is no more free version once the trial period has expired.
Too bad, the description says there are free features, but after the trial I have to pay or can no longer use it 
;-)

**Comment by ThScEo** [comment]
I think it s not abusive to ask 4€ to support my work?
If you think it’s abusive then don’t use it :)
