### ISSUE TITLE
Error when checking updates: 'Model' object has no attribute 'emit'

### ISSUE THREAD

**Issue by Gerchan** [ThScEo/AutoForge#9]
Getting this error when updating loop, bot then crashes.
![AutoForge_p2HSzTBaSA](https://user-images.githubusercontent.com/29171156/187725811-2d3b5992-9828-4dc0-8a97-aeadc0efe086.png)

**Comment by ThScEo** [comment]
Hi, sorry for that. A new release will be available today to resolve this bug.

**Comment by Gerchan** [comment]
Awesone, thanks dude! :)

**Comment by ThScEo** [comment]
Hi, there is an issue related to this, [see here](https://github.com/ThScEo/AutoForge/issues/3).
